"""Add profile_image_url to doctor

Revision ID: ad24f504610a
Revises: 6c120f943def
Create Date: 2026-09-02 10:23:05.880087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad24f504610a'
down_revision: Union[str, None] = '6c120f943def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medai_doctors', sa.Column('profile_image_url', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_medai_patients_user_id'), 'medai_patients', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medai_patients_user_id'), table_name='medai_patients')
    op.drop_column('medai_doctors', 'profile_image_url')
    # ### end Alembic commands ###
